/**
 * FireCheck 4D E-leaflet — translations (EN / FR)
 * Edit this file to manage all translatable strings.
 */
(function () {
  'use strict';

  window.FireCheck4D_TRANSLATIONS = {
    en: {
      nav_benefits: 'Benefits',
      nav_compliance: 'Data to Compliance',
      nav_smart_features: 'Smart Features',
      nav_capabilities: '3 Certainty',
      nav_game: 'Online Game',
      nav_more_info: 'More Information',
      hero_tag: 'Geneva Invention — BIM Fire Safety',
      hero_subtitle: 'A BIM Fire Safety Checker — revolutionising the design and regulatory process by BIM automated checking',
      hero_badge: 'A BIM Fire Safety Checker',
      about_tag: 'ABOUT',
      about_title: 'What is FireCheck 4D?',
      about_lead1: 'The FireCheck 4D revolutionises the design and regulatory process by implementing Building Information Modelling (BIM) automated checking functions for compliance with fire safety requirements, enabling precise spatial analysis as well as material tracking for design flexibility and certainty.',
      about_lead2: 'It executes a standardised and automated regulatory process, transforming design and checking workflow from manual to automated, through creating machine-readable rules.',
      about_lead3: 'By bridging digital precision with physical assurance, we are building a world where every building stands resilient from concept to legacy.',
      about_video_placeholder: '[Video]',
      benefits_tag: 'Benefits',
      benefits_title: 'Benefits',
      benefits_lead1: 'Passive fire design is a critical yet often overlooked aspect of modern construction. The FireCheck 4D significantly reduces human error and enhances productivity and certainty in design, construction as well as adaption and alteration in the whole life span of the building.',
      benefits_lead2: 'Through automating the design and regulatory process, the overall productivity can be increased by 30%. A better fire design and robust management can also help to reduce preventable economic loss and casualties due to fire incidents.',
      stat_productivity: 'Productivity',
      stat_victims: 'Annual global victims',
      stat_loss: 'Estimated economic loss',
      compliance_tag: 'From Data to Compliance',
      compliance_title: 'Translate Regulatory Requirements into Machine-readable Parameters for Automated Vetting',
      compliance_lead: 'BIM model contains rich digital entities. By analysing regulatory requirements and critical parameters, a structured data schema can be defined, enabling precise data extraction and spatial analysis for automated compliance checking.',
      global_tag: 'Global Adoption',
      global_title: 'Codify regulatory requirements in various natural languages',
      global_lead: 'Regulatory requirements in various natural languages and human-understandable logic statements can be seamlessly translated into machine-readable checking rules. This flexible framework facilitates global adoption, enabling rapid digitisation and easy translation of code requirements to cater different performance requirements.',
      smart_tag: 'SMART FEATURES',
      smart_lead: 'The FireCheck 4D is equipped with a series of smart functions to facilitate data entry and plan preparation, including automatic filling of essential parameters based on room use, identification of missing parameters and data irregularities and systematic import of the checking result schedules back to the BIM file for preparation and processing of plan submissions.',
      smart_title: 'Three pillars for seamless BIM fire safety workflow',
      smart_input_title: '<span class="feature-icon">↑</span> Smart INPUT',
      smart_input_desc: 'Instant and automatic filling of essential parameters from IFC files for seamless parameter input.',
      smart_check_title: '<span class="feature-icon">✓</span> Smart CHECK',
      smart_check_desc: 'Identification of missing parameters and data irregularities in the BIM model for seamless automatic correction.',
      smart_import_title: '<span class="feature-icon">↓</span> Smart IMPORT',
      smart_import_desc: 'Systematic import of schedules into IFC for production and handling of submission documents.',
      three_certitude_tag: 'THE 3-CERTAINTY',
      three_certitude_lead: 'The FireCheck 4D is digital powerhouse which ensures every building project can achieve the "3-Certainty" in design, construction, and life-cycle.',
      certitude_design: 'Design certainty',
      certitude_construction: 'Construction certainty',
      certitude_lifecycle: 'Lifecycle certainty',
      capabilities_tag: 'Design & analysis',
      capabilities_title: 'Simulate and analyse for statutory compliance',
      ifc_title: 'IFC Data Schema',
      ifc_lead: 'Data schema and parameter setting make space, use, evacuation sequence, building elements and construction machine-readable. Our unique data structure successfully extracts essential data from BIM model for automated computation and analysis.',
      evacuation_title: 'Evacuation Sequence Analysis',
      evacuation_lead: 'Evacuation sequence analysis is inherently complex, as building escape routes form a matrix of possible scenarios. By extracting the egress direction of each opening between consecutive spaces, an \'in-out\' logic is established.',
      evacuation_lead2: 'This logic links all spaces along the evacuation path within the BIM model, enabling automated determination of people flow sequences. Such analysis is critical for evaluating travel distances, cumulative population in each space, and the required width and number of escape routes or staircases.',
      space_title: 'Space to Space Approach',
      space_lead: 'Hong Kong Fire Safety Code stipulates that the width of each exit route, as well as the combined width of all exit routes, must be determined based on occupancy capacity and the number of exits provided. The \'in-out\' logic supports this process by computing the possible maximum population in each individual space, ensuring that exit widths are sufficient for safe evacuation.',
      travel_title: 'Travel Distance Assessment',
      travel_lead: 'Unlike paper submission which relies on manual judgment and measurement of travel distances, we have adopted various geometrical principles and developed our own pathfinding algorithms to automate the travel distance assessment.',
      fig_farthest: 'Breadth-first search (BFS) algorithm - Identify the farthest part of a room',
      fig_shortest: 'A-star algorithm - Find the shortest path of exit',
      fig_skeleton: 'Straight skeleton algorithm - Find the middle path of a room',
      fire_resist_title: 'Fire Resisting Construction',
      fire_resist_lead: 'In Hong Kong, every building should be divided into fire compartments by fire barriers to inhibit the spread of fire. By extracting compartment information and building element data, the integrity and continuity of these fire separations will be automatically assessed.',
      traceability_title: 'Fire Rated Material Traceability',
      traceability_lead: 'By providing a digital linkage between design and on-site construction, a reliable system is established which tracks critical material attributes including specifications, suppliers, sampling and test results.',
      traceability_lead2: 'We link BIM models with RFID technology to verify every critical fire safety element is "Built-to-Design". This guarantees flawless execution on-site, eliminating common construction pitfalls that compromise fire safety.',
      firefighting_title: 'Firefighting and Rescue',
      firefighting_lead: 'By delineating emergency vehicular access in the BIM model, spatial analysis will be conducted to ensure the envelope of the building is adequately served by fire appliance.',
      alterations_title: 'Alterations and Additions',
      alterations_lead: 'Before implementation of alterations and additions works, the impact of the proposed changes can be simulated for assessment, such as extensions increasing compartment size, use changes raising population loads, or repartitioning affecting travel distances.',
      alterations_lead2: 'This predictive approach spots out possible contraventions and ensures the proposed changes are compatible to fire safety design of the building.',
      game_tag: 'Try it',
      game_title: 'Play our Fire Safety game',
      game_lead: 'Experience our fire safety concepts in an interactive way. Click below to open the online game in a new tab.',
      game_btn: 'Play Fire Safety Game →',
      achievements_tag: 'ACHIEVEMENTS',
      achievement1_award1: 'Best Innovation Award',
      achievement1_award2: 'Gold Award in API/Plugin Category',
      achievement1_event: 'BIM Automation Arena 2025',
      achievement1_org: 'The Hong Kong Institute of Building Information Modelling',
      achievement2_award1: 'Winner in Research and Innovation Category',
      achievement2_award2: 'Value Enhancement Award',
      achievement2_event: 'The HKIS Building Surveyor Awards 2025',
      achievement2_org: 'The Hong Kong Institute of Surveyors',
      more_info: 'More Information / Plus d\'informations',
      experience_tool_tag: 'EXPERIENCE THE TOOL',
      experience_tool_lead: 'How the FireCheck 4D works? Click the icon below to start a mini game and experience the checking of travel distance.',
      footer_main: 'FireCheck 4D — A BIM Fire Safety Checker. Buildings Department · Tsinghua University · VIRCON.',
      footer_hosted: 'Hosted at'
    },
    fr: {
      nav_benefits: 'Avantages',
      nav_compliance: 'Données vers conformité',
      nav_smart_features: 'Fonctionnalités intelligentes',
      nav_capabilities: '3 Certitudes',
      nav_game: 'Jeu en ligne',
      nav_more_info: 'Plus d\'informations',
      hero_tag: 'Invention de Genève — Sécurité incendie BIM',
      hero_subtitle: 'Un vérificateur de sécurité incendie BIM — révolutionnant le processus de conception et réglementaire par la vérification automatisée BIM.',
      hero_badge: 'Un vérificateur de sécurité incendie BIM',
      about_tag: 'À PROPOS',
      about_title: 'Qu\'est-ce que FireCheck 4D ?',
      about_lead1: 'FireCheck 4D révolutionne le processus de conception et réglementaire en mettant en œuvre des fonctions de vérification automatisée du Building Information Modelling (BIM) pour la conformité aux exigences de sécurité incendie, permettant une analyse spatiale précise ainsi qu\'un suivi des matériaux pour la flexibilité et la certitude de conception.',
      about_lead2: 'Il exécute un processus réglementaire standardisé et automatisé, transformant le flux de travail de conception et de vérification du manuel à l\'automatisé, grâce à la création de règles lisibles par machine.',
      about_lead3: 'En reliant la précision numérique à l\'assurance physique, nous construisons un monde où chaque bâtiment reste résilient du concept au legs.',
      about_video_placeholder: '[Vidéo]',
      benefits_tag: 'Avantages',
      benefits_title: 'Avantages',
      benefits_lead1: 'La conception passive contre l\'incendie est un aspect critique mais souvent négligé de la construction moderne. FireCheck 4D réduit considérablement les erreurs humaines et améliore la productivité et la certitude dans la conception, la construction ainsi que l\'adaptation et la modification sur l\'ensemble du cycle de vie du bâtiment.',
      benefits_lead2: 'En automatisant le processus de conception et réglementaire, la productivité globale peut être augmentée de 30 %. Une meilleure conception incendie et une gestion robuste peuvent également contribuer à réduire les pertes économiques évitables et les victimes d\'incendies.',
      stat_productivity: 'Productivité',
      stat_victims: 'Victimes mondiales annuelles',
      stat_loss: 'Perte économique estimée',
      compliance_tag: 'Des données à la conformité',
      compliance_title: 'Traduire les exigences réglementaires en paramètres lisibles par machine pour une vérification automatisée',
      compliance_lead: 'Le modèle BIM contient des entités numériques riches. En analysant les exigences réglementaires et les paramètres critiques, un schéma de données structuré peut être défini, permettant une extraction de données précise et une analyse spatiale pour la vérification automatisée de la conformité.',
      global_tag: 'Adoption mondiale',
      global_title: 'Codifier les exigences réglementaires dans diverses langues naturelles',
      global_lead: 'Les exigences réglementaires dans diverses langues naturelles et les énoncés logiques compréhensibles par l\'homme peuvent être traduits de manière transparente en règles de vérification lisibles par machine. Ce cadre flexible facilite l\'adoption mondiale, permettant une numérisation rapide et une traduction aisée des exigences du code pour répondre aux différentes exigences de performance.',
      smart_tag: 'FONCTIONNALITÉS INTELLIGENTES',
      smart_lead: 'FireCheck 4D est doté d\'une série de fonctions intelligentes pour faciliter la saisie des données et la préparation des plans, notamment le remplissage automatique des paramètres essentiels selon l\'usage des pièces, l\'identification des paramètres manquants et des irrégularités de données, et l\'import systématique des plannings de résultats de vérification dans le fichier BIM pour la préparation et le traitement des soumissions de plans.',
      smart_title: 'Trois piliers pour un flux de travail BIM de sécurité incendie fluide',
      smart_input_title: '<span class="feature-icon">↑</span> Smart INPUT',
      smart_input_desc: 'Remplissage instantané et automatique des paramètres essentiels à partir des fichiers IFC pour une saisie de paramètres fluide.',
      smart_check_title: '<span class="feature-icon">✓</span> Smart CHECK',
      smart_check_desc: 'Identification des paramètres manquants et des irrégularités de données dans le modèle BIM pour une correction automatique fluide.',
      smart_import_title: '<span class="feature-icon">↓</span> Smart IMPORT',
      smart_import_desc: 'Import systématique des plannings dans IFC pour la production et la gestion des documents de soumission.',
      three_certitude_tag: 'LES 3 CERTITUDES',
      three_certitude_lead: 'FireCheck 4D est une plateforme numérique qui garantit que chaque projet de construction puisse atteindre les « 3 Certitudes » en conception, construction et cycle de vie.',
      certitude_design: 'Certitude de conception',
      certitude_construction: 'Certitude de construction',
      certitude_lifecycle: 'Certitude du cycle de vie',
      capabilities_tag: 'Conception et analyse',
      capabilities_title: 'Simuler et analyser pour la conformité réglementaire',
      ifc_title: 'Schéma de données IFC',
      ifc_lead: 'Le schéma de données et le paramétrage rendent l\'espace, l\'usage, la séquence d\'évacuation, les éléments de construction et la construction lisibles par machine. Notre structure de données unique extrait avec succès les données essentielles du modèle BIM pour le calcul et l\'analyse automatisés.',
      evacuation_title: 'Analyse de séquence d\'évacuation',
      evacuation_lead: 'L\'analyse de séquence d\'évacuation est intrinsèquement complexe, les routes d\'évacuation formant une matrice de scénarios possibles. En extrayant la direction d\'évacuation de chaque ouverture entre espaces consécutifs, une logique « entrée-sortie » est établie.',
      evacuation_lead2: 'Cette logique relie tous les espaces le long du chemin d\'évacuation dans le modèle BIM, permettant une détermination automatisée des séquences de flux de personnes. Cette analyse est essentielle pour évaluer les distances de déplacement, la population cumulée dans chaque espace, ainsi que la largeur et le nombre requis de routes d\'évacuation ou d\'escaliers.',
      space_title: 'Approche espace à espace',
      space_lead: 'Le Code de sécurité incendie de Hong Kong stipule que la largeur de chaque route de sortie, ainsi que la largeur combinée de toutes les routes de sortie, doit être déterminée en fonction de la capacité d\'occupation et du nombre de sorties. La logique « entrée-sortie » soutient ce processus en calculant la population maximale possible dans chaque espace, garantissant que les largeurs de sortie sont suffisantes pour une évacuation sûre.',
      travel_title: 'Évaluation de la distance de déplacement',
      travel_lead: 'Contrairement au dépôt sur papier qui repose sur le jugement et la mesure manuels des distances de déplacement, nous avons adopté divers principes géométriques et développé nos propres algorithmes de recherche de chemin pour automatiser l\'évaluation de la distance de déplacement.',
      fig_farthest: 'Algorithme de recherche en largeur (BFS) - Identifier la partie la plus éloignée d\'une pièce',
      fig_shortest: 'Algorithme A* - Trouver le chemin de sortie le plus court',
      fig_skeleton: 'Algorithme du squelette droit - Trouver le chemin médian d\'une pièce',
      fire_resist_title: 'Construction résistante au feu',
      fire_resist_lead: 'À Hong Kong, chaque bâtiment doit être divisé en compartiments coupe-feu par des barrières pare-feu pour limiter la propagation du feu. En extrayant les informations sur les compartiments et les données des éléments de construction, l\'intégrité et la continuité de ces séparations coupe-feu seront évaluées automatiquement.',
      traceability_title: 'Traçabilité des matériaux classés au feu',
      traceability_lead: 'En établissant une liaison numérique entre la conception et la construction sur site, un système fiable est mis en place qui suit les attributs critiques des matériaux, notamment les spécifications, les fournisseurs, les échantillons et les résultats des tests.',
      traceability_lead2: 'Nous lions les modèles BIM à la technologie RFID pour vérifier que chaque élément critique de sécurité incendie est « conforme au projet ». Cela garantit une exécution sans faille sur site, en éliminant les pièges courants de la construction qui compromettent la sécurité incendie.',
      firefighting_title: 'Lutte contre l\'incendie et sauvetage',
      firefighting_lead: 'En délimitant l\'accès véhiculaire d\'urgence dans le modèle BIM, une analyse spatiale sera réalisée pour s\'assurer que l\'enveloppe du bâtiment est correctement desservie par les engins de secours.',
      alterations_title: 'Modifications et ajouts',
      alterations_lead: 'Avant la mise en œuvre des travaux de modifications et d\'ajouts, l\'impact des changements proposés peut être simulé pour évaluation, notamment les extensions augmentant la taille des compartiments, les changements d\'usage augmentant les charges de population, ou le repartitionnement affectant les distances de déplacement.',
      alterations_lead2: 'Cette approche prédictive repère les éventuelles infractions et garantit que les changements proposés sont compatibles avec la conception de sécurité incendie du bâtiment.',
      game_tag: 'Essayez',
      game_title: 'Jouez à notre jeu Fire Safety',
      game_lead: 'Découvrez nos concepts de sécurité incendie de manière interactive. Cliquez ci-dessous pour ouvrir le jeu en ligne dans un nouvel onglet.',
      game_btn: 'Jouer au jeu Fire Safety →',
      achievements_tag: 'RÉALISATIONS',
      achievement1_award1: 'Prix de la meilleure innovation',
      achievement1_award2: 'Prix d\'or dans la catégorie API/Plugin',
      achievement1_event: 'BIM Automation Arena 2025',
      achievement1_org: 'The Hong Kong Institute of Building Information Modelling',
      achievement2_award1: 'Lauréat dans la catégorie Recherche et innovation',
      achievement2_award2: 'Prix de la valeur ajoutée',
      achievement2_event: 'The HKIS Building Surveyor Awards 2025',
      achievement2_org: 'The Hong Kong Institute of Surveyors',
      more_info: 'Plus d\'informations / More Information',
      experience_tool_tag: 'EXPÉRIMENTEZ L\'OUTIL',
      experience_tool_lead: 'Comment fonctionne FireCheck 4D ? Cliquez sur l\'icône ci-dessous pour lancer un mini-jeu et découvrir la vérification de la distance de déplacement.',
      footer_main: 'FireCheck 4D — Un vérificateur de sécurité incendie BIM. Buildings Department · Tsinghua University · VIRCON.',
      footer_hosted: 'Hébergé sur'
    }
  };
})();
