/**
 * FireCheck 4D E-leaflet — translations (EN / FR)
 * Edit this file to manage all translatable strings.
 */
(function () {
  'use strict';

  window.FireCheck4D_TRANSLATIONS = {
    en: {
      nav_benefits: 'Benefits',
      nav_compliance: 'Data to Compliance',
      nav_smart_features: 'Smart Features',
      nav_capabilities: 'Capabilities',
      nav_game: 'Online Game',
      nav_more_info: 'More Information',
      hero_tag: 'Geneva Invention — BIM Fire Safety',
      hero_subtitle: 'A BIM Fire Safety Checker — translating regulatory requirements into machine-readable parameters for automated vetting and design certainty.',
      hero_badge: 'A BIM Fire Safety Checker',
      benefits_tag: 'Benefits',
      benefits_title: 'Protect our homes through better fire design',
      benefits_lead: 'Protect our homes through better fire design. FireCheck 4D supports productivity gains and highlights the global impact of fire safety.',
      stat_productivity: 'Productivity',
      stat_victims: 'Annual global victims',
      stat_loss: 'Estimated economic loss',
      compliance_tag: 'From Data to Compliance',
      compliance_title: 'Translate regulatory requirements into machine-readable parameters for automated vetting',
      compliance_lead: 'BIM models and structured data schemas enable automated compliance checking. Human expertise and machine processing work together on the BIM model to deliver code compliance status.',
      global_tag: 'Global Adoption',
      global_title: 'Codify regulatory requirements in various natural languages',
      global_lead: 'Regulatory requirements can be translated and codified for rapid deployment and easy adaptation across jurisdictions.',
      smart_tag: 'Smart Features',
      smart_title: 'Three pillars for seamless BIM fire safety workflow',
      smart_input_title: '<span class="feature-icon">↑</span> Smart INPUT',
      smart_input_desc: 'Instant and automatic filling of essential parameters from IFC files for seamless parameter input.',
      smart_check_title: '<span class="feature-icon">✓</span> Smart CHECK',
      smart_check_desc: 'Identification of missing parameters and data irregularities in the BIM model for seamless automatic correction.',
      smart_import_title: '<span class="feature-icon">↓</span> Smart IMPORT',
      smart_import_desc: 'Systematic import of schedules into IFC for production and handling of submission documents.',
      certitude_design: 'Design certainty',
      certitude_construction: 'Construction certainty',
      certitude_lifecycle: 'Lifecycle certainty',
      capabilities_tag: 'Design & analysis',
      capabilities_title: 'Simulate and analyse for statutory compliance',
      evacuation_title: 'Evacuation sequence analysis',
      evacuation_lead: 'Simulate effort for identifying evacuation paths — optimum design support for evacuation routes and key areas.',
      ifc_title: 'IFC data schema',
      ifc_lead: 'Create structuring parameters for machine-learning translation of regulatory requirements — graphics to data.',
      space_title: 'Space to space approach',
      space_lead: 'Compute optimal population to determine required width of safety exits — optimize circulation for occupant movement and safe egress.',
      travel_title: 'Travel distance assessment',
      travel_lead: 'Deploy pathfinding algorithms for precise statutory compliance.',
      fig_farthest: 'Identify the farthest point',
      fig_shortest: 'Shortest path',
      fig_skeleton: 'Straight skeleton',
      fire_resist_title: 'Fire resisting construction',
      fire_resist_lead: 'Automate integrity assessment of fire compartmentation.',
      traceability_title: 'Fire rated material traceability',
      traceability_lead: 'Link design model with actual construction for verified compliance — material tracking and site verification.',
      firefighting_title: 'Firefighting and rescue',
      firefighting_lead: 'Spatial analysis of building facade served by emergency vehicular access.',
      alterations_title: 'Alterations and additions',
      alterations_lead: 'Simulate impact to ensure continuous statutory compliance — extensions, repartitioning, staircase capacity.',
      game_tag: 'Try it',
      game_title: 'Play our Fire Safety game',
      game_lead: 'Experience our fire safety concepts in an interactive way. Click below to open the online game in a new tab.',
      game_btn: 'Play Fire Safety Game →',
      more_info: 'More Information / Plus d\'informations',
      footer_main: 'FireCheck 4D — A BIM Fire Safety Checker. Buildings Department · Tsinghua University · VIRCON.',
      footer_hosted: 'Hosted at'
    },
    fr: {
      nav_benefits: 'Avantages',
      nav_compliance: 'Données vers conformité',
      nav_smart_features: 'Fonctionnalités intelligentes',
      nav_capabilities: 'Capacités',
      nav_game: 'Jeu en ligne',
      nav_more_info: 'Plus d\'informations',
      hero_tag: 'Invention de Genève — Sécurité incendie BIM',
      hero_subtitle: 'Un vérificateur de sécurité incendie BIM — traduisant les exigences réglementaires en paramètres lisibles par machine pour une vérification automatisée et une certitude de conception.',
      hero_badge: 'Un vérificateur de sécurité incendie BIM',
      benefits_tag: 'Avantages',
      benefits_title: 'Protégez notre maison grâce à une meilleure conception du feu',
      benefits_lead: 'Protégez notre maison grâce à une meilleure conception du feu. FireCheck 4D soutient les gains de productivité et met en évidence l\'impact mondial de la sécurité incendie.',
      stat_productivity: 'Productivité',
      stat_victims: 'Victimes mondiales annuelles',
      stat_loss: 'Perte économique estimée',
      compliance_tag: 'Des données à la conformité',
      compliance_title: 'Traduire les exigences réglementaires en paramètres lisibles par machine pour une vérification automatisée',
      compliance_lead: 'Les modèles BIM et les schémas de données structurés permettent une vérification automatisée de la conformité. L\'expertise humaine et le traitement machine travaillent ensemble sur le modèle BIM pour fournir le statut de conformité.',
      global_tag: 'Adoption mondiale',
      global_title: 'Codifier les exigences réglementaires dans diverses langues naturelles',
      global_lead: 'Les exigences réglementaires peuvent être traduites et codifiées pour un déploiement rapide et une adaptation facile entre les juridictions.',
      smart_tag: 'Fonctionnalités intelligentes',
      smart_title: 'Trois piliers pour un flux de travail BIM de sécurité incendie fluide',
      smart_input_title: '<span class="feature-icon">↑</span> Smart INPUT',
      smart_input_desc: 'Remplissage instantané et automatique des paramètres essentiels à partir des fichiers IFC pour une saisie de paramètres fluide.',
      smart_check_title: '<span class="feature-icon">✓</span> Smart CHECK',
      smart_check_desc: 'Identification des paramètres manquants et des irrégularités de données dans le modèle BIM pour une correction automatique fluide.',
      smart_import_title: '<span class="feature-icon">↓</span> Smart IMPORT',
      smart_import_desc: 'Import systématique des plannings dans IFC pour la production et la gestion des documents de soumission.',
      certitude_design: 'Certitude de conception',
      certitude_construction: 'Certitude de construction',
      certitude_lifecycle: 'Certitude du cycle de vie',
      capabilities_tag: 'Conception et analyse',
      capabilities_title: 'Simuler et analyser pour la conformité réglementaire',
      evacuation_title: 'Analyse de séquence d\'évacuation',
      evacuation_lead: 'Simuler l\'effort pour identifier les chemins d\'évacuation — soutien optimal à la conception des routes d\'évacuation et des zones clés.',
      ifc_title: 'Schéma de données IFC',
      ifc_lead: 'Créer des paramètres de structuration pour la traduction par apprentissage automatique des exigences réglementaires — graphiques vers données.',
      space_title: 'Approche espace à espace',
      space_lead: 'Calculer la population optimale pour déterminer la largeur requise des sorties de sécurité — optimiser la circulation pour le mouvement des occupants et l\'évacuation sûre.',
      travel_title: 'Évaluation de la distance de déplacement',
      travel_lead: 'Déployer des algorithmes de recherche de chemin pour une conformité réglementaire précise.',
      fig_farthest: 'Identifier le point le plus éloigné',
      fig_shortest: 'Chemin le plus court',
      fig_skeleton: 'Squelette droit',
      fire_resist_title: 'Construction résistante au feu',
      fire_resist_lead: 'Automatiser l\'évaluation d\'intégrité du compartimentage incendie.',
      traceability_title: 'Traçabilité des matériaux classés au feu',
      traceability_lead: 'Lier le modèle de conception à la construction réelle pour une conformité vérifiée — suivi des matériaux et vérification sur site.',
      firefighting_title: 'Lutte contre l\'incendie et sauvetage',
      firefighting_lead: 'Analyse spatiale de la façade du bâtiment desservie par l\'accès véhiculaire d\'urgence.',
      alterations_title: 'Modifications et ajouts',
      alterations_lead: 'Simuler l\'impact pour assurer une conformité réglementaire continue — extensions, repartition, capacité des escaliers.',
      game_tag: 'Essayez',
      game_title: 'Jouez à notre jeu Fire Safety',
      game_lead: 'Découvrez nos concepts de sécurité incendie de manière interactive. Cliquez ci-dessous pour ouvrir le jeu en ligne dans un nouvel onglet.',
      game_btn: 'Jouer au jeu Fire Safety →',
      more_info: 'Plus d\'informations / More Information',
      footer_main: 'FireCheck 4D — Un vérificateur de sécurité incendie BIM. Buildings Department · Tsinghua University · VIRCON.',
      footer_hosted: 'Hébergé sur'
    }
  };
})();
