/**
 * UrbanCool Dynamics E-leaflet — translations (EN / FR)
 * Edit this file to manage all translatable strings.
 */
(function () {
  'use strict';

  window.UrbanCool_TRANSLATIONS = {
    en: {
      nav_hero: 'Overview',
      nav_about: 'About',
      nav_painpoints: 'Pain points',
      nav_climate: 'Climate',
      nav_cooling: 'Multi-Scale Cooling',
      nav_integration: 'Integration',
      nav_science: 'Scientific Robustness',
      nav_design: 'Design Review',
      nav_recognition: 'Recognition',
      nav_more_info: 'More Information',
      hero_tag: 'Geneva Invention — Urban Ventilation',
      hero_subtitle: 'Create COOLER & HEALTHIER Cities in NO TIME — Building Ventilation Analysis Revolutionised From Weeks to Minutes.',
      hero_badge: 'A BIM Building Permeability Checker',
      about_tag: 'About',
      about_lead: 'An openBIM Permeability Checker — fuses fluid dynamics with openBIM technology to enhance building design for optimal airflow, enabling fast and user-friendly assessments that improve performance and resilience of the built environment against urban heat amplified by climate change.',
      painpoints_tag: "Practitioners' Pain points",
      painpoints_title: 'Seeking a quick and practical tool that allows design flexibility',
      painpoints_point1: 'Current practice heavily relies on 2D projection, which may overestimate blockage between buildings and lacks 3D detail.',
      painpoints_point2: 'Although 3D Computational Fluid Dynamics (CFD) offers an alternative, its simulation and analysis are time-consuming, leading to missing the golden period for testing design options.',
      climate_tag: 'Climate-response',
      climate_title: 'Imminent Challenge to Urban Liveability',
      climate_lead: 'Global cities are facing a growing threat from rising temperatures — increasing at 23% to 103% above the global average. Just five consecutive hot nights can raise mortality rates by up to 7%, while every 1°C increase may drive a 9.2% surge in residential electricity consumption.',
      stat_trend: '+23 to +103%',
      stat_trend_label: 'Cities vs global trend',
      stat_heatwave_label: 'Dangerous heat wave markers',
      cooling_tag: 'Multi-Scale Cooling',
      cooling_title: 'Testified in Hong Kong, a high-density city role model',
      cooling_lead: 'From streetscape to neighbourhood to city scale — assess permeability zones (High, Mid, Low) for optimal airflow and urban cooling.',
      band_science: 'Nature-inspired Equation',
      band_integration: 'Integration with City Spatial Data Infrastructure',
      integration_tag: 'Intégration / Integration',
      integration_title: 'Integration with City Spatial Data Infrastructure',
      integration_lead: 'Connect building design with urban context — site-level, street connectivity, urban form, topographical, and adjacent land use insights.',
      insight_site: 'Site-level insights',
      insight_street: 'Street connectivity insights',
      insight_urban: 'Urban form insights',
      insight_topo: 'Topographical insights',
      insight_adjacent: 'Adjacent land uses insights',
      science_tag: 'Robustesse Scientifique / Scientific Robustness',
      science_title: 'Nature-inspired Equation',
      science_lead: 'A windbreak-derived method to assess blockage porosity. Airflow physics informs friction and turning costs simulation.',
      formula_lcp: 'LCP% = Σ Li / L open space',
      science_physics: 'Physics to Algorithm — The Least Cost Path, From Skin Friction to Friction Cost, From Form Drag to Turning Cost.',
      band_design: 'Instant Design Review & Generation',
      design_tag: 'Analyse & Génération Instantanées / Instant Design Review & Generation',
      design_title: 'From Codes, Needs and Site to Design',
      workflow_codes: 'From Codes to Design',
      workflow_codes_desc: 'Ingest regulations, zoning bylaws into machine-readable rules.',
      workflow_needs: 'From Needs to Design',
      workflow_needs_desc: 'Translate user needs into spatial and functional blocks for 3D massing.',
      workflow_site: 'From Site to Design',
      workflow_site_desc: 'Auto-generate massing options based on site context, configuration, orientations.',
      validation_text: 'Scientific Validation: LCP method compared with CFD — high agreement (R=0.92 and 0.85).',
      recognition_tag: 'Recognition and Impacts',
      recognition_title: 'Recognition and Impacts',
      recognition_headline: 'Enable rapid iterations to generate building designs incorporating spatial data, code compliance, and quick permeability analysis.',
      recognition_lead: 'UrbanCool Dynamics supports instant design generation at early stages, delivering sustainable value with minimal effort and maximum impact. Through broad industry participation, the tool has gained strong practitioner support.',
      recognition_award: 'Research published at the 2025 CIB World Building Congress received the Best Paper Award in the category "Nature-Based Solutions for Climate Resilience in Buildings and Communities". This recognition highlights the tool\'s contribution to UN Sustainable Development Goals:',
      sdg_3_title: 'Good Health and Well-being',
      sdg_3_desc: 'Improving air quality for better health and well-being',
      sdg_11_title: 'Sustainable Cities and Communities',
      sdg_11_desc: 'Enhancing liveability in sustainable cities',
      sdg_13_title: 'Climate Action',
      sdg_13_desc: 'Climate-responsive building design for climate action',
      recognition_chart_placeholder: 'Effort/Effect vs. Time chart — add assets/images/recognition_impacts_chart.png',
      more_info: 'More Information / Plus d\'informations',
      footer_main: 'UrbanCool Dynamics — A BIM Building Permeability Checker. Buildings Department · ARUP · VIRCON · CUHK · Ronald Lu & Partners.',
      footer_hosted: 'Hosted at'
    },
    fr: {
      nav_hero: 'Aperçu',
      nav_about: 'À propos',
      nav_painpoints: 'Points de douleur',
      nav_climate: 'Climat',
      nav_cooling: 'Refroidissement multi-échelle',
      nav_integration: 'Intégration',
      nav_science: 'Robustesse scientifique',
      nav_design: 'Revue de conception',
      nav_recognition: 'Reconnaissance',
      nav_more_info: 'Plus d\'informations',
      hero_tag: 'Invention de Genève — Ventilation urbaine',
      hero_subtitle: 'Créer des villes plus FRAÎCHES et plus SAINES en un rien de temps — Analyse de ventilation des bâtiments révolutionnée, de semaines à minutes.',
      hero_badge: 'Un vérificateur BIM de perméabilité des bâtiments',
      about_tag: 'À propos',
      about_lead: 'Un vérificateur de perméabilité openBIM — fusionne la dynamique des fluides avec la technologie openBIM pour améliorer la conception des bâtiments en vue d\'un flux d\'air optimal, permettant des évaluations rapides et conviviales qui améliorent les performances et la résilience de l\'environnement bâti face à la chaleur urbaine amplifiée par le changement climatique.',
      painpoints_tag: 'Points de douleur des praticiens',
      painpoints_title: 'Recherche d\'un outil rapide et pratique permettant une flexibilité de conception',
      painpoints_point1: 'La pratique actuelle repose fortement sur la projection 2D, qui peut surestimer le blocage entre les bâtiments et manque de détails en 3D.',
      painpoints_point2: 'Bien que la dynamique des fluides computationnelle (CFD) 3D offre une alternative, sa simulation et son analyse sont chronophages, ce qui fait manquer la période idéale pour tester les options de conception.',
      climate_tag: 'Réponse au climat',
      climate_title: 'Défi imminent pour la qualité de vie urbaine',
      climate_lead: 'Les villes du monde entier font face à une menace croissante des températures en hausse — une augmentation de 23 % à 103 % au-dessus de la moyenne mondiale. Cinq nuits chaudes consécutives peuvent augmenter les taux de mortalité jusqu\'à 7 %, tandis que chaque augmentation de 1 °C peut entraîner une hausse de 9,2 % de la consommation électrique résidentielle.',
      stat_trend: '+23 à +103 %',
      stat_trend_label: 'Villes vs tendance mondiale',
      stat_heatwave_label: 'Marqueurs de vague de chaleur dangereuse',
      cooling_tag: 'Refroidissement multi-échelle',
      cooling_title: 'Attesté à Hong Kong, modèle de ville à haute densité',
      cooling_lead: 'De l\'échelle paysagère au quartier à l\'échelle urbaine — évaluer les zones de perméabilité (haute, moyenne, basse) pour un flux d\'air et un refroidissement urbain optimaux.',
      band_science: 'Équation inspirée de la nature',
      band_integration: 'Intégration avec l\'infrastructure de données spatiales de la ville',
      integration_tag: 'Intégration',
      integration_title: 'Intégration avec l\'infrastructure de données spatiales de la ville',
      integration_lead: 'Connectez la conception des bâtiments au contexte urbain — informations au niveau du site, connectivité des rues, forme urbaine, topographiques et utilisations adjacentes des sols.',
      insight_site: 'Informations au niveau du site',
      insight_street: 'Connectivité des rues',
      insight_urban: 'Forme urbaine',
      insight_topo: 'Informations topographiques',
      insight_adjacent: 'Utilisations adjacentes des sols',
      science_tag: 'Robustesse scientifique',
      science_title: 'Équation inspirée de la nature',
      science_lead: 'Une méthode dérivée des brise-vent pour évaluer la porosité des obstacles. La physique de l\'écoulement d\'air informe la simulation des coûts de friction et de virage.',
      formula_lcp: 'LCP% = Σ Li / L espace ouvert',
      science_physics: 'De la physique à l\'algorithme — Le chemin du moindre coût, De la friction cutanée au coût de friction, De la traînée de forme au coût de virage.',
      band_design: 'Analyse et génération instantanées de conception',
      design_tag: 'Analyse et génération instantanées de conception',
      design_title: 'Des codes, besoins et site à la conception',
      workflow_codes: 'Des codes à la conception',
      workflow_codes_desc: 'Ingérer les réglementations, les règlements de zonage en règles lisibles par machine.',
      workflow_needs: 'Des besoins à la conception',
      workflow_needs_desc: 'Traduire les besoins des utilisateurs en blocs spatiaux et fonctionnels pour la massification 3D.',
      workflow_site: 'Du site à la conception',
      workflow_site_desc: 'Générer automatiquement les options de massification selon le contexte du site, la configuration et les orientations.',
      validation_text: 'Validation scientifique : méthode LCP comparée au CFD — forte concordance (R=0,92 et 0,85).',
      recognition_tag: 'Reconnaissance et impacts',
      recognition_title: 'Reconnaissance et impacts',
      recognition_headline: 'Permettre des itérations rapides pour générer des conceptions de bâtiments intégrant des données spatiales, la conformité aux codes et une analyse de perméabilité rapide.',
      recognition_lead: 'UrbanCool Dynamics prend en charge la génération de conception instantanée dès les premières étapes, offrant une valeur durable avec un effort minimal et un impact maximal. Grâce à une large participation de l\'industrie, l\'outil a obtenu un fort soutien des praticiens.',
      recognition_award: 'La recherche publiée au Congrès mondial du bâtiment CIB 2025 a reçu le prix du meilleur article dans la catégorie « Solutions fondées sur la nature pour la résilience climatique des bâtiments et des communautés ». Cette reconnaissance souligne la contribution de l\'outil aux objectifs de développement durable des Nations Unies :',
      sdg_3_title: 'Bonne santé et bien-être',
      sdg_3_desc: 'Améliorer la qualité de l\'air pour une meilleure santé et un meilleur bien-être',
      sdg_11_title: 'Villes et communautés durables',
      sdg_11_desc: 'Améliorer la qualité de vie dans les villes durables',
      sdg_13_title: 'Mesures relatives à la lutte contre les changements climatiques',
      sdg_13_desc: 'Conception de bâtiments adaptés au climat pour l\'action climatique',
      recognition_chart_placeholder: 'Graphique Effort/Effet vs. Temps — ajouter assets/images/recognition_impacts_chart.png',
      more_info: 'Plus d\'informations / More Information',
      footer_main: 'UrbanCool Dynamics — Un vérificateur BIM de perméabilité des bâtiments. Buildings Department · ARUP · VIRCON · CUHK · Ronald Lu & Partners.',
      footer_hosted: 'Hébergé sur'
    }
  };
})();
