/**
 * UrbanCool Dynamics E-leaflet — translations (EN / FR)
 * Edit this file to manage all translatable strings.
 */
(function () {
  'use strict';

  window.UrbanCool_TRANSLATIONS = {
    en: {
      nav_hero: 'Overview',
      nav_about: 'About',
      nav_problem: 'Problem',
      nav_solutions: 'Solution',
      nav_painpoints: 'Pain points',
      nav_climate: 'Climate',
      nav_cooling: 'Multi-Scale Cooling',
      nav_integration: 'City Spatial Data Integration',
      nav_science: 'Scientific Robustness',
      nav_design: 'Instant Design Review and Generation',
      nav_recognition: 'Recognition',
      nav_achievements: 'Achievements',
      nav_more_info: 'More Information',
      hero_tag: 'Geneva Invention — Urban Ventilation',
      hero_subtitle: 'A BIM Building Permeability Checker – revolutionising building ventilation analysis and creating cooler and healthier cities <span class="hero-highlight">in no time</span>',
      about_tag: 'About',
      about_title: 'What Is UrbanCool Dynamics?',
      about_lead1: 'UrbanCool Dynamics fuses fluid dynamics with openBIM technology to enhance building design for optimal airflow, enabling fast and user-friendly assessments that improve performance and resilience against urban heat amplified by climate change.',
      about_lead2: 'Based on scientific research and openBIM algorithm, the UrbanCool Dynamics is validated using Computational Fluid Dynamics (CFD) to assess air permeability of a building proposal through numerical analysis of the friction and turning cost of air pathways.',
      about_lead3: 'It envisions a future where designers can predict and optimise urban air movement of cities in real time — creating cooler, healthier, and more sustainable cities powered by science and open collaboration in the era of climate change.',
      painpoints_tag: "Practitioners' Pain points",
      painpoints_title: 'Early Design Review',
      painpoints_point1: 'The most cost-effective moment for intervention is the very early design phase, when form, orientation, and massing are still flexible and inexpensive to change.',
      painpoints_point2: 'However, using CFD simulation to assess airflow and ventilation between buildings can cost tens of thousands of dollars and take weeks. By the time results are ready, building layouts are often fixed and cannot be reshaped to improve ventilation.',
      climate_tag: 'THE PROBLEM',
      climate_title: 'Rising Temperature Crisis',
      climate_chart_subtitle: 'Mean Temperature Anomaly for Global Cities',
      climate_chart_subsubtitle: "Cities' temperatures rise steeper than global average",
      climate_lead: 'Extreme heat is becoming one of the most dangerous climate threats worldwide. Global cities are facing a growing threat from rising temperatures — increasing at 23% to 103% above the global average. Just five consecutive hot nights can raise mortality rates by up to 7%, while every 1°C increase may drive a 9.2% surge in residential electricity consumption.',
      climate_lead2: 'Dense clusters of tall buildings trap heat and stall the wind, driving urban temperatures to rise much faster than the global average and exposing millions to dangerous thermal stress. The urban heat island effect compounds global warming, intensifying heatwaves and pushing up energy demand.',
      stat_trend: '+23 to +103%',
      stat_trend_label: 'compare to global trend',
      stat_heatwave_label: 'Dangerous heat wave markers',
      solutions_band: 'Our Solution',
      solutions_tag: 'Our Solution',
      solutions_title: 'UrbanCool Dynamics',
      solutions_lead1: 'The UrbanCool Dynamics changes this paradigm by combining advanced airflow science with building design tools to enhance airflow performance around buildings, helping cities stay cool and liveable in a warming climate.',
      solutions_lead2: 'It enables architects to evaluate airflow performance at the concept or early schematic stage, guiding site planning, orientation, and form toward better lifecycle cost, energy, and carbon outcomes.',
      solutions_media1_placeholder: '[Graphic: Create COOLER & HEALTHIER Cities in NO TIME]',
      solutions_media2_placeholder: '[Chart: Design stages PD, SD, DD, CD, GBP Submission]',
      cooling_tag: 'Multi-Scale Cooling',
      cooling_title: 'Multi-Scale Cooling',
      cooling_lead: 'It is testified in Hong Kong, a high-density city role model, enhancing building permeability in LOW, MIDDLE and HIGH zones for thermal comfort in Streetscape, Neighbourhood and City scales.',
      cooling_lead_ext: 'Testified in Hong Kong, a high-density city role model (with plot ratio in the order of 10+), enhancing Building Permeability in LOW, MIDDLE & HIGH zones for thermal comfort in Streetscape, Neighbourhood & City scales.',
      cooling_offer: 'The UrbanCool Dynamics is offered to industry at no cost as critical digital infrastructure for climate adaptation, helping to reduce health impacts, energy use, and productivity losses from extreme heat.',
      band_science: 'SCIENTIFIC ROBUSTNESS',
      band_integration: 'Integration with City Spatial Data Infrastructure',
      integration_tag: 'CITY SPATIAL DATA INTEGRATION',
      integration_title: 'Integration with City Spatial Data Infrastructure',
      integration_lead: 'Connect building design with urban context — site-level, street connectivity, urban form, topographical, and adjacent land use insights.',
      integration_lead_ext: 'UrbanCool Dynamics retrieves site information such as site geometry, streets, urban form, land uses, and topography from an integrated city spatial data infrastructure to dynamically sculpt massing, the public realm, and the microclimate to deliver cool, walkable, and socially vibrant spaces under extreme heat.',
      insight_site: 'Site Level',
      insight_site_desc: 'Extract accurate site profile to inform massing, setbacks and porosity opportunities for urban cooling',
      insight_street: 'Street Connectivity',
      insight_street_desc: 'Inform climate resilient design and planning with mapped street widths, pedestrian and airflows, and potential thermal hot spots',
      insight_urban: 'Urban Form',
      insight_urban_desc: 'Retrieve 3D city model around the site for their volumetric opportunities for urban ventilation and thermal relief',
      insight_adjacent: 'Adjacent Land Uses',
      insight_adjacent_desc: 'Consolidate land use and potential crowd movement and heat exposure layers to inform public realm and amenities planning',
      insight_topo: 'Topographical',
      insight_topo_desc: 'Feed site and city\'s terrain data for solar and wind analysis',
      science_tag: 'SCIENTIFIC ROBUSTNESS',
      science_title: 'SCIENTIFIC ROBUSTNESS',
      science_sub1_title: 'Nature-Inspired — A Windbreak-Derived Method',
      science_sub1_lead: 'Wind slows down due to friction and turning. Inspired by the wind-protection effect of tree windbreaks, we use these two factors to evaluate building permeability.',
      science_media_windbreak: '[Diagram: Wind flow and windbreak]',
      science_sub2_title: 'The Least Cost Path — From Physics to Algorithm',
      science_sub2_lead: 'Our new 3D Least Cost Path (LCP) method evaluates building permeability using two metrics, i.e. Friction Cost which represents airflow resistance, and Turning Cost which reflects path configuration complexities.',
      science_voxel_lead: 'The UrbanCool Dynamics voxelises the 3D building model, traces potential airpaths, assigns friction costs near facades, and applies turning costs at each change in direction. It then calculates the cost along each airpath; a lower overall cost means better permeability.',
      science_media_model: '[Model video]',
      science_validation_title: 'Scientific Validation',
      science_validation_lead: 'By comparing LCP and CFD outputs using linear, power-law and logarithmic models, the strong agreement (R² = 0.92 and 0.85 for the power-law and logarithmic models respectively) indicates a close alignment between the developed LCP method and the widely adopted CFD methodology.',
      science_media_lcp_cfd: '[LCP vs. CFD diagram]',
      formula_lcp: 'LCP% = Σ Li / L open space',
      band_design: 'Instant Design Review & Generation',
      design_tag: 'INSTANT DESIGN REVIEW AND GENERATION',
      design_title: 'From Codes, Needs and Site to Design',
      design_lead: 'Apart from building permeability analysis, the design process is further streamlined and integrated. Design options can be generated instantly in response to user needs while complying with other regulatory requirements on overall development density and building height as well as spatial requirements including building setback, open space, natural lighting and ventilation, etc.',
      workflow_codes: 'From Codes to Design',
      workflow_codes_desc: 'Parse regulations, zoning bylaws, building codes, accessibility standards, etc. into machine-readable rules',
      workflow_needs: 'From Needs to Design',
      workflow_needs_desc: 'Instant-translate users\' needs into spatial and functional blocks and 3D massing',
      workflow_site: 'From Site to Design',
      workflow_site_desc: 'Auto-generate massing options in response to site contexts, configuration and orientations',
      workflow_expand: 'Expand',
      workflow_collapse: 'Collapse',
      needs_caption_studio: 'Studio',
      needs_caption_1room: '1 room unit',
      needs_caption_2room: '2 room unit',
      needs_caption_3room: '3 room unit',
      validation_text: 'Scientific Validation: LCP method compared with CFD — high agreement (R=0.92 and 0.85).',
      recognition_tag: 'Recognition and Impacts',
      recognition_title: 'Recognition and Impacts',
      recognition_headline: 'UrbanCool Dynamics contributes to 4 United Nation Sustainable Development Goals: SDG 11 (Sustainable Cities and Communities), SDG 13 (Climate Action), SDG 9 (Industry, Innovation and Infrastructure), and SDG 3 (Good Health and Well-being).',
      recognition_lead: 'UrbanCool Dynamics supports instant design generation at early stages, delivering sustainable value with minimal effort and maximum impact. Through broad industry participation, the tool has gained strong practitioner support.',
      recognition_award: 'Research published at the 2025 CIB World Building Congress received the Best Paper Award in the category "Nature-Based Solutions for Climate Resilience in Buildings and Communities". This recognition highlights the tool\'s contribution to UN Sustainable Development Goals:',
      sdg_3_title: 'Good Health and Well-being',
      sdg_3_desc: 'Mitigates heat-related health risks by lowering exposure to extreme urban temperatures, especially for vulnerable groups.',
      sdg_11_title: 'Sustainable Cities and Communities',
      sdg_11_desc: 'Supports more resilient and sustainable urban layouts by optimising ventilation and reducing urban heat in dense cities.',
      sdg_13_title: 'Climate Action',
      sdg_13_desc: 'Acts as climate adaptation infrastructure, helping cities cope with heat amplified by climate change via better design decisions.',
      sdg_9_title: 'Industry, Innovation and Infrastructure',
      sdg_9_desc: 'Provides innovative digital infrastructure (BIM-based automated checking, machine-readable codes) that modernises high-performance design and regulatory control workflows.',
      recognition_chart_placeholder: 'Effort/Effect vs. Time chart — add assets/images/recognition_impacts_chart.png',
      uc_achievements_tag: 'ACHIEVEMENTS',
      uc_achievement1_award1: 'Best Paper Award',
      uc_achievement1_event: 'World Building Congress 2025',
      uc_achievement1_org: 'International Council for Research and Innovation in Building and Construction',
      uc_achievement2_award1: 'Best Innovation Award',
      uc_achievement2_award2: 'Gold Award in API/Plugin Category',
      uc_achievement2_event: 'BIM Automation Arena 2025',
      uc_achievement2_org: 'The Hong Kong Institute of Building Information Modelling',
      uc_achievement3_award1: 'Winner in Research and Innovation Category',
      uc_achievement3_award2: 'Value Enhancement Award',
      uc_achievement3_event: 'The HKIS Building Surveyor Awards 2025',
      uc_achievement3_org: 'The Hong Kong Institute of Surveyors',
      more_info: 'More Information / Plus d\'informations',
      more_info_tools: 'Download the Tools',
      more_info_tutorial: 'Tutorial video',
      footer_main: 'UrbanCool Dynamics — A BIM Building Permeability Checker. Buildings Department · Ronald Lu & Partners · ARUP · VIRCON · The Chinese University of Hong Kong.',
      footer_hosted: 'Hosted at'
    },
    fr: {
      nav_hero: 'Aperçu',
      nav_about: 'À propos',
      nav_problem: 'Problème',
      nav_solutions: 'Solution',
      nav_painpoints: 'Points de douleur',
      nav_climate: 'Climat',
      nav_cooling: 'Refroidissement multi-échelle',
      nav_integration: 'Intégration des données spatiales urbaines',
      nav_science: 'Robustesse scientifique',
      nav_design: 'Analyse et génération instantanées de conception',
      nav_recognition: 'Reconnaissance',
      nav_achievements: 'Réalisations',
      nav_more_info: 'Plus d\'informations',
      hero_tag: 'Invention de Genève — Ventilation urbaine',
      hero_subtitle: 'Un vérificateur BIM de perméabilité des bâtiments – révolutionnant l\'analyse de la ventilation des bâtiments et créant des villes plus fraîches et plus saines <span class="hero-highlight">en un rien de temps</span>',
      about_tag: 'À propos',
      about_title: 'Qu\'est-ce qu\'UrbanCool Dynamics ?',
      about_lead1: 'UrbanCool Dynamics fusionne la dynamique des fluides avec la technologie openBIM pour améliorer la conception des bâtiments en vue d\'un flux d\'air optimal, permettant des évaluations rapides et conviviales qui améliorent les performances et la résilience face à la chaleur urbaine amplifiée par le changement climatique.',
      about_lead2: 'Fondé sur la recherche scientifique et l\'algorithme openBIM, UrbanCool Dynamics est validé par la dynamique des fluides computationnelle (CFD) pour évaluer la perméabilité à l\'air d\'un projet de bâtiment grâce à l\'analyse numérique du coût de friction et de virage des chemins d\'air.',
      about_lead3: 'Il envisage un avenir où les concepteurs pourront prédire et optimiser le mouvement de l\'air urbain des villes en temps réel — créant des villes plus fraîches, plus saines et plus durables, portées par la science et la collaboration ouverte à l\'ère du changement climatique.',
      painpoints_tag: 'Points de douleur des praticiens',
      painpoints_title: 'Revue de conception en amont',
      painpoints_point1: 'Le moment le plus rentable pour intervenir est la phase de conception très précoce, lorsque la forme, l\'orientation et la massification sont encore flexibles et peu coûteuses à modifier.',
      painpoints_point2: 'Cependant, l\'utilisation de la simulation CFD pour évaluer les flux d\'air et la ventilation entre les bâtiments peut coûter des dizaines de milliers de dollars et prendre des semaines. Lorsque les résultats sont prêts, les implantations des bâtiments sont souvent figées et ne peuvent plus être modifiées pour améliorer la ventilation.',
      climate_tag: 'Problème',
      climate_title: 'Crise de la hausse des températures',
      climate_chart_subtitle: 'Anomalie de température moyenne pour les villes mondiales',
      climate_chart_subsubtitle: "Les températures des villes augmentent plus rapidement que la moyenne mondiale",
      climate_lead: 'Les vagues de chaleur extrême sont en train de devenir l\'une des menaces climatiques les plus dangereuses dans le monde. Les villes du monde entier font face à une menace croissante des températures en hausse — une augmentation de 23 % à 103 % au-dessus de la moyenne mondiale. Cinq nuits chaudes consécutives peuvent augmenter les taux de mortalité jusqu\'à 7 %, tandis que chaque augmentation de 1 °C peut entraîner une hausse de 9,2 % de la consommation électrique résidentielle.',
      climate_lead2: 'Les concentrations denses de grands bâtiments piègent la chaleur et bloquent le vent, faisant monter les températures urbaines bien plus vite que la moyenne mondiale et exposant des millions de personnes à un stress thermique dangereux. L\'effet d\'îlot de chaleur urbain s\'ajoute au réchauffement planétaire, intensifiant les vagues de chaleur et augmentant la demande énergétique.',
      stat_trend: '+23 à +103 %',
      stat_trend_label: 'par rapport à la tendance mondiale',
      stat_heatwave_label: 'Marqueurs de vague de chaleur dangereuse',
      solutions_band: 'Notre solution',
      solutions_tag: 'Notre solution',
      solutions_title: 'UrbanCool Dynamics',
      solutions_lead1: 'UrbanCool Dynamics change ce paradigme en combinant la science avancée des flux d\'air et les outils de conception des bâtiments pour améliorer les performances de ventilation autour des bâtiments, aidant les villes à rester fraîches et habitables dans un climat qui se réchauffe.',
      solutions_lead2: 'Il permet aux architectes d\'évaluer les performances de ventilation dès la phase de concept ou d\'esquisse, en orientant la planification du site, l\'orientation et la forme vers de meilleurs résultats en termes de coût du cycle de vie, d\'énergie et de carbone.',
      solutions_media1_placeholder: '[Graphique : Créer des villes plus FRAÎCHES et plus SAINES en un rien de temps]',
      solutions_media2_placeholder: '[Graphique : Étapes de conception PD, SD, DD, CD, soumission GBP]',
      cooling_tag: 'Refroidissement multi-échelle',
      cooling_title: 'Refroidissement multi-échelle',
      cooling_lead: 'Cette approche est attestée à Hong Kong, ville modèle à haute densité, en améliorant la perméabilité des bâtiments dans les zones BASSE, MOYENNE et HAUTE pour le confort thermique aux échelles des rues, du quartier et de la ville.',
      cooling_lead_ext: 'Attesté à Hong Kong, modèle de ville à haute densité (avec un ratio de construction de l\'ordre de 10+), améliorant la perméabilité des bâtiments dans les zones BASSE, MOYENNE et HAUTE pour le confort thermique aux échelles paysagère, quartier et ville.',
      cooling_offer: 'UrbanCool Dynamics est offert à l\'industrie gratuitement comme infrastructure numérique essentielle pour l\'adaptation au climat, contribuant à réduire les impacts sur la santé, la consommation énergétique et les pertes de productivité dues aux vagues de chaleur extrêmes.',
      band_science: 'ROBUSTESSE SCIENTIFIQUE',
      band_integration: 'Intégration avec l\'infrastructure de données spatiales de la ville',
      integration_tag: 'INTÉGRATION DES DONNÉES SPATIALES URBAINES',
      integration_title: 'Intégration avec l\'infrastructure de données spatiales de la ville',
      integration_lead: 'Connectez la conception des bâtiments au contexte urbain — informations au niveau du site, connectivité des rues, forme urbaine, topographiques et utilisations adjacentes des sols.',
      integration_lead_ext: 'UrbanCool Dynamics récupère les informations du site telles que la géométrie du site, les rues, la forme urbaine, les utilisations des sols et la topographie depuis une infrastructure de données spatiales urbaines intégrée pour façonner dynamiquement la massification, l\'espace public et le microclimat afin de créer des espaces frais, praticables et socialement dynamiques en cas de chaleur extrême.',
      insight_site: 'Niveau du site',
      insight_site_desc: 'Extraire le profil précis du site pour informer la massification, les reculs et les opportunités de porosité pour le rafraîchissement urbain',
      insight_street: 'Connectivité des rues',
      insight_street_desc: 'Informer la conception et la planification résilientes au climat avec les largeurs de rues, les flux piétons et d\'air et les points chauds thermiques potentiels',
      insight_urban: 'Forme urbaine',
      insight_urban_desc: 'Récupérer le modèle 3D de la ville autour du site pour les opportunités volumétriques de ventilation urbaine et de soulagement thermique',
      insight_adjacent: 'Utilisations adjacentes des sols',
      insight_adjacent_desc: 'Consolider l\'utilisation des sols, les mouvements de foule et les couches d\'exposition à la chaleur pour informer l\'espace public et la planification des équipements',
      insight_topo: 'Topographique',
      insight_topo_desc: 'Alimenter les données de terrain du site et de la ville pour l\'analyse solaire et éolienne',
      science_tag: 'ROBUSTESSE SCIENTIFIQUE',
      science_title: 'ROBUSTESSE SCIENTIFIQUE',
      science_sub1_title: 'Inspiré de la nature — Méthode dérivée des brise-vent',
      science_sub1_lead: 'Le vent ralentit en raison de la friction et des changements de direction. En nous inspirant de l\'effet de protection des brise-vent arborés, nous utilisons ces deux facteurs pour évaluer la perméabilité des bâtiments.',
      science_media_windbreak: '[Diagramme : Flux du vent et brise-vent]',
      science_sub2_title: 'Le chemin du moindre coût — De la physique à l\'algorithme',
      science_sub2_lead: 'Notre nouvelle méthode 3D du chemin du moindre coût (LCP) évalue la perméabilité des bâtiments à l\'aide de deux indicateurs : le coût de friction (résistance au flux d\'air) et le coût de virage (complexité de la configuration des chemins).',
      science_voxel_lead: 'UrbanCool Dynamics voxélise le modèle 3D du bâtiment, trace les chemins d\'air potentiels, attribue les coûts de friction près des façades et applique les coûts de virage à chaque changement de direction. Il calcule ensuite le coût le long de chaque chemin ; un coût global plus faible signifie une meilleure perméabilité.',
      science_media_model: '[Vidéo du modèle]',
      science_validation_title: 'Validation scientifique',
      science_validation_lead: 'En comparant les sorties LCP et CFD à l\'aide de modèles linéaire, puissance et logarithmique, la forte concordance (R² = 0,92 et 0,85 pour les modèles puissance et logarithmique respectivement) indique un alignement étroit entre la méthode LCP développée et la méthodologie CFD largement adoptée.',
      science_media_lcp_cfd: '[Diagramme LCP vs. CFD]',
      formula_lcp: 'LCP% = Σ Li / L espace ouvert',
      band_design: 'Analyse et génération instantanées de conception',
      design_tag: 'ANALYSE ET GÉNÉRATION INSTANTANÉES DE CONCEPTION',
      design_title: 'Des codes, besoins et site à la conception',
      design_lead: 'Outre l\'analyse de perméabilité des bâtiments, le processus de conception est encore rationalisé et intégré. Les options de conception peuvent être générées instantanément en réponse aux besoins des utilisateurs tout en respectant les exigences réglementaires en matière de densité de développement, de hauteur des bâtiments ainsi que les exigences spatiales (recul, espace ouvert, éclairage et ventilation naturels, etc.).',
      workflow_codes: 'Des codes à la conception',
      workflow_codes_desc: 'Traduire les réglementations, les règlements de zonage, les codes du bâtiment, les normes d\'accessibilité, etc. en règles lisibles par machine',
      workflow_needs: 'Des besoins à la conception',
      workflow_needs_desc: 'Traduire instantanément les besoins des utilisateurs en blocs spatiaux et fonctionnels et en massification 3D',
      workflow_site: 'Du site à la conception',
      workflow_site_desc: 'Générer automatiquement les options de massification en réponse aux contextes du site, à la configuration et aux orientations',
      workflow_expand: 'Développer',
      workflow_collapse: 'Réduire',
      needs_caption_studio: 'Studio',
      needs_caption_1room: '1 pièce',
      needs_caption_2room: '2 pièces',
      needs_caption_3room: '3 pièces',
      validation_text: 'Validation scientifique : méthode LCP comparée au CFD — forte concordance (R=0,92 et 0,85).',
      recognition_tag: 'Reconnaissance et impacts',
      recognition_title: 'Reconnaissance et impacts',
      recognition_headline: 'UrbanCool Dynamics contribue à 4 ODD de l’ONU : ODD 11 (Villes et communautés durables), ODD 13 (Mesures relatives à la lutte contre les changements climatiques), ODD 9 (Industrie, innovation et infrastructure) et ODD 3 (Bonne santé et bien-être).',
      recognition_lead: 'UrbanCool Dynamics prend en charge la génération de conception instantanée dès les premières étapes, offrant une valeur durable avec un effort minimal et un impact maximal. Grâce à une large participation de l\'industrie, l\'outil a obtenu un fort soutien des praticiens.',
      recognition_award: 'La recherche publiée au Congrès mondial du bâtiment CIB 2025 a reçu le prix du meilleur article dans la catégorie « Solutions fondées sur la nature pour la résilience climatique des bâtiments et des communautés ». Cette reconnaissance souligne la contribution de l\'outil aux objectifs de développement durable des Nations Unies :',
      sdg_3_title: 'Bonne santé et bien-être',
      sdg_3_desc: 'Réduit les risques sanitaires liés à la chaleur en diminuant l’exposition aux températures urbaines extrêmes, en particulier pour les groupes vulnérables.',
      sdg_11_title: 'Villes et communautés durables',
      sdg_11_desc: 'Favorise des configurations urbaines plus résilientes et durables en optimisant la ventilation et en réduisant la chaleur urbaine dans les villes denses.',
      sdg_13_title: 'Mesures relatives à la lutte contre les changements climatiques',
      sdg_13_desc: 'Constitue une infrastructure d’adaptation climatique, aidant les villes à faire face à la chaleur amplifiée par le changement climatique grâce à de meilleures décisions de conception.',
      sdg_9_title: 'Industrie, innovation et infrastructure',
      sdg_9_desc: 'Fournit une infrastructure numérique innovante (contrôle automatisé basé sur le BIM, codes lisibles par machine) qui modernise les flux de conception haute performance et de contrôle réglementaire.',
      recognition_chart_placeholder: 'Graphique Effort/Effet vs. Temps — ajouter assets/images/recognition_impacts_chart.png',
      uc_achievements_tag: 'RÉALISATIONS',
      uc_achievement1_award1: 'Prix du meilleur article',
      uc_achievement1_event: 'Congrès mondial du bâtiment 2025',
      uc_achievement1_org: 'Conseil international de la recherche et de l\'innovation dans la construction',
      uc_achievement2_award1: 'Prix de la meilleure innovation',
      uc_achievement2_award2: 'Prix d\'or dans la catégorie API/Plugin',
      uc_achievement2_event: 'BIM Automation Arena 2025',
      uc_achievement2_org: 'The Hong Kong Institute of Building Information Modelling',
      uc_achievement3_award1: 'Lauréat dans la catégorie Recherche et innovation',
      uc_achievement3_award2: 'Prix de la valeur ajoutée',
      uc_achievement3_event: 'The HKIS Building Surveyor Awards 2025',
      uc_achievement3_org: 'The Hong Kong Institute of Surveyors',
      more_info: 'Plus d\'informations / More Information',
      more_info_tools: 'Téléchargement des outils généraux',
      more_info_tutorial: 'Vidéo tutoriel',
      footer_main: 'UrbanCool Dynamics — Un vérificateur BIM de perméabilité des bâtiments. Buildings Department · Ronald Lu & Partners · ARUP · VIRCON · The Chinese University of Hong Kong.',
      footer_hosted: 'Hébergé sur'
    }
  };
})();
