/**
 * UrbanCool Dynamics E-leaflet — translations (EN / FR)
 * Edit this file to manage all translatable strings.
 */
(function () {
  'use strict';

  window.UrbanCool_TRANSLATIONS = {
    en: {
      nav_hero: 'Overview',
      nav_climate: 'Climate',
      nav_cooling: 'Multi-Scale Cooling',
      nav_integration: 'Integration',
      nav_science: 'Scientific Robustness',
      nav_design: 'Design Review',
      nav_more_info: 'More Information',
      hero_tag: 'Geneva Invention — Urban Ventilation',
      hero_subtitle: 'Create COOLER & HEALTHIER Cities in NO TIME — Building Ventilation Analysis Revolutionised From Weeks to Minutes.',
      hero_badge: 'A BIM Building Permeability Checker',
      climate_tag: 'Climate-response',
      climate_title: 'Addressing rising temperature crisis',
      climate_lead: 'Urban temperatures are rising faster than global averages. UrbanCool Dynamics helps designers address the heat crisis through data-driven ventilation analysis.',
      stat_trend: '+23 to 103%',
      stat_trend_label: 'Cities vs global trend',
      stat_heatwave_label: 'Dangerous heat wave markers',
      cooling_tag: 'Multi-Scale Cooling',
      cooling_title: 'Testified in Hong Kong, a high-density city role model',
      cooling_lead: 'From streetscape to neighbourhood to city scale — assess permeability zones (High, Mid, Low) for optimal airflow and urban cooling.',
      band_integration: 'Integration with City Spatial Data Infrastructure',
      integration_tag: 'Intégration / Integration',
      integration_title: 'Integration with City Spatial Data Infrastructure',
      integration_lead: 'Connect building design with urban context — site-level, street connectivity, urban form, topographical, and adjacent land use insights.',
      insight_site: 'Site-level insights',
      insight_street: 'Street connectivity insights',
      insight_urban: 'Urban form insights',
      insight_topo: 'Topographical insights',
      insight_adjacent: 'Adjacent land uses insights',
      science_tag: 'Robustesse Scientifique / Scientific Robustness',
      science_title: 'Nature-inspired Equation',
      science_lead: 'A windbreak-derived method to assess blockage porosity. Airflow physics informs friction and turning costs simulation.',
      formula_lcp: 'LCP% = Σ Li / L open space',
      science_physics: 'Physics to Algorithm — The Least Cost Path, From Skin Friction to Friction Cost, From Form Drag to Turning Cost.',
      band_design: 'Instant Design Review & Generation',
      design_tag: 'Analyse & Génération Instantanées / Instant Design Review & Generation',
      design_title: 'From Codes, Needs and Site to Design',
      workflow_codes: 'From Codes to Design',
      workflow_codes_desc: 'Ingest regulations, zoning bylaws into machine-readable rules.',
      workflow_needs: 'From Needs to Design',
      workflow_needs_desc: 'Translate user needs into spatial and functional blocks for 3D massing.',
      workflow_site: 'From Site to Design',
      workflow_site_desc: 'Auto-generate massing options based on site context, configuration, orientations.',
      validation_text: 'Scientific Validation: LCP method compared with CFD — high agreement (R=0.92 and 0.85).',
      more_info: 'More Information / Plus d\'informations',
      footer_main: 'UrbanCool Dynamics — A BIM Building Permeability Checker. Buildings Department · ARUP · VIRCON · CUHK · Ronald Lu & Partners.',
      footer_hosted: 'Hosted at'
    },
    fr: {
      nav_hero: 'Aperçu',
      nav_climate: 'Climat',
      nav_cooling: 'Refroidissement multi-échelle',
      nav_integration: 'Intégration',
      nav_science: 'Robustesse scientifique',
      nav_design: 'Revue de conception',
      nav_more_info: 'Plus d\'informations',
      hero_tag: 'Invention de Genève — Ventilation urbaine',
      hero_subtitle: 'Créer des villes plus FRAÎCHES et plus SAINES en un rien de temps — Analyse de ventilation des bâtiments révolutionnée, de semaines à minutes.',
      hero_badge: 'Un vérificateur BIM de perméabilité des bâtiments',
      climate_tag: 'Réponse au climat',
      climate_title: 'Face à la crise de la hausse des températures',
      climate_lead: 'Les températures urbaines augmentent plus rapidement que les moyennes mondiales. UrbanCool Dynamics aide les concepteurs à faire face à la crise de la chaleur grâce à une analyse de ventilation basée sur les données.',
      stat_trend: '+23 à 103 %',
      stat_trend_label: 'Villes vs tendance mondiale',
      stat_heatwave_label: 'Marqueurs de vague de chaleur dangereuse',
      cooling_tag: 'Refroidissement multi-échelle',
      cooling_title: 'Attesté à Hong Kong, modèle de ville à haute densité',
      cooling_lead: 'De l\'échelle paysagère au quartier à l\'échelle urbaine — évaluer les zones de perméabilité (haute, moyenne, basse) pour un flux d\'air et un refroidissement urbain optimaux.',
      band_integration: 'Intégration avec l\'infrastructure de données spatiales de la ville',
      integration_tag: 'Intégration',
      integration_title: 'Intégration avec l\'infrastructure de données spatiales de la ville',
      integration_lead: 'Connectez la conception des bâtiments au contexte urbain — informations au niveau du site, connectivité des rues, forme urbaine, topographiques et utilisations adjacentes des sols.',
      insight_site: 'Informations au niveau du site',
      insight_street: 'Connectivité des rues',
      insight_urban: 'Forme urbaine',
      insight_topo: 'Informations topographiques',
      insight_adjacent: 'Utilisations adjacentes des sols',
      science_tag: 'Robustesse scientifique',
      science_title: 'Équation inspirée de la nature',
      science_lead: 'Une méthode dérivée des brise-vent pour évaluer la porosité des obstacles. La physique de l\'écoulement d\'air informe la simulation des coûts de friction et de virage.',
      formula_lcp: 'LCP% = Σ Li / L espace ouvert',
      science_physics: 'De la physique à l\'algorithme — Le chemin du moindre coût, De la friction cutanée au coût de friction, De la traînée de forme au coût de virage.',
      band_design: 'Analyse et génération instantanées de conception',
      design_tag: 'Analyse et génération instantanées de conception',
      design_title: 'Des codes, besoins et site à la conception',
      workflow_codes: 'Des codes à la conception',
      workflow_codes_desc: 'Ingérer les réglementations, les règlements de zonage en règles lisibles par machine.',
      workflow_needs: 'Des besoins à la conception',
      workflow_needs_desc: 'Traduire les besoins des utilisateurs en blocs spatiaux et fonctionnels pour la massification 3D.',
      workflow_site: 'Du site à la conception',
      workflow_site_desc: 'Générer automatiquement les options de massification selon le contexte du site, la configuration et les orientations.',
      validation_text: 'Validation scientifique : méthode LCP comparée au CFD — forte concordance (R=0,92 et 0,85).',
      more_info: 'Plus d\'informations / More Information',
      footer_main: 'UrbanCool Dynamics — Un vérificateur BIM de perméabilité des bâtiments. Buildings Department · ARUP · VIRCON · CUHK · Ronald Lu & Partners.',
      footer_hosted: 'Hébergé sur'
    }
  };
})();
